apiVersion: v1
kind: Service
metadata:
  name: node-exporter-runner
  namespace: monitoring
  labels:
    app: node-exporter-runner
spec:
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
---
apiVersion: v1
kind: Endpoints
metadata:
  name: node-exporter-runner
  namespace: monitoring
subsets:
  - addresses:
      - ip: 10.0.2.11
      - ip: 10.0.2.12
      - ip: 10.0.2.13
    ports:
      - name: metrics
        port: 9100
