---
# tasks file for rancher
- name: Add Helm repos
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Add Rancher Helm repo
  kubernetes.core.helm_repository:
    name: rancher-latest
    repo_url: "https://releases.rancher.com/server-charts/latest"

- name: Ensure cert-manager namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ cert_manager_namespace }}"
    state: present

- name: Install cert-manager CRDs
  kubernetes.core.k8s:
    state: present
    src: "https://github.com/cert-manager/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.crds.yaml"

- name: Install cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: "{{ cert_manager_namespace }}"
    wait: true
    values:
      installCRDs: false

- name: Ensure Rancher namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ rancher_namespace }}"
    state: present

- name: Install Rancher
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-latest/rancher
    release_namespace: "{{ rancher_namespace }}"
    wait: true
    values:
      hostname: "{{ rancher_hostname }}"
      replicas: "{{ rancher_replicas }}"
      bootstrapPassword: "ChangeMe123!"
      tls: "{{ rancher_tls_source }}"
